# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoto', '0002_auto_20180719_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='intro',
            field=models.FileField(blank=True, null=True, upload_to='intros/'),
        ),
        migrations.AddField(
            model_name='channel',
            name='logo',
            field=models.FileField(default='tst', upload_to='logos/'),
            preserve_default=False,
        ),
    ]
