# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-09 08:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoto', '0003_auto_20180720_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to='thumbs')),
            ],
        ),
    ]
