# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-29 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoto', '0004_videthumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200)),
                ('is_seen', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='VideThumb',
        ),
    ]
