# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-09-01 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoto', '0005_auto_20180829_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
